name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5

      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"
          # https://github.com/Hefezopf/stock-analyse.git
          # git clone https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/Kotlin-CalculateDistanceOfPoints.git
          git clone https://Hefezopf@github.com/Kotlin-CalculateDistanceOfPoints/Kotlin-CalculateDistanceOfPoints.git
          cd Kotlin-CalculateDistanceOfPoints
          # git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          # git remote update
          # git merge ${{ env.ORIGINAL_REPO_NAME }}/main
          # git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: Your workspace name