name: Sync Repos

on:
  #push:
    #branches:
      #- master
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

    # Can be triggered manually
  workflow_dispatch:
    inputs:
      symbolsParam:
        description: 'SYMBOLS - List of stock symbols like: "*DBK BEI". Own stocks marked *'
        required: true
        default: '*DBK BEI'
      percentageParam:
        description: 'PERCENTAGE - "1" means 1 percent'     
        required: true
        default: '1'
      stochasticParam:
        description: 'STOCHASTIC14 - "9" means 9/91 percent (only single digit allowed!)'     
        required: true
        default: '9'
      RSIParam:
        description: 'RSI14 - "25" means 25/75 quote. (only 30 and less allowed!)'
        required: true
        default: '25'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5

      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/Kotlin-CalculateDistanceOfPoints
          ls Kotlin-CalculateDistanceOfPoints -lisa
          cp Kotlin-CalculateDistanceOfPoints/build/kotlin/compileKotlin/last-build.bin . 
          # git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          # git remote update
          # git merge ${{ env.ORIGINAL_REPO_NAME }}/master
          git add last-build.bin
          git commit -am "test"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: Hefezopf

